receivers:
  jaeger:
    protocols:
      thrift_compact:
        endpoint: 0.0.0.0:6831

processors:

exporters:
  otlp:
    endpoint: telegraf-opentelemetry:4317
    insecure: true

extensions:

service:
  extensions: []
  pipelines:
    traces:
      receivers: [jaeger]
      processors: []
      exporters: [otlp]
