receivers:
  jaeger:
    protocols:
      thrift_compact:
        endpoint: 0.0.0.0:6831

  prometheus:
    config:
      scrape_configs:
      - job_name: "otel-collector"
        scrape_interval: 10s
        static_configs:
        - targets: ["hotrod:8083"]

processors:

exporters:
  influxdb/iox:
    org: "myorg"
    bucket: "mybucket"
    protocol: "line-protocol"
    line_protocol_server_url: "http://influxdb-iox:8080"
    line_protocol_auth_token: "my-token"

extensions:

service:
  extensions: []
  pipelines:
    traces:
      receivers: [jaeger]
      processors: []
      exporters: [influxdb/iox]

    metrics:
      receivers: [prometheus]
      processors: []
      exporters: [influxdb/iox]
